config/routes.rb
Rails.application.routes.draw do
  resources :statements
  resources :cars
  devise_for :users, controllers: {registrations: 'users/registrations'}

   root 'statements#index'

end

app/models/statement.rb
class Statement < ActiveRecord::Base
  belongs_to :user
  # spécifie que paperclip aura a géré :picture
 # que le fichier original sera redimensionné en 1920x1800
 # et que thumb sere redimensionné en 200x200
 # si le fichier ne devait pas être présent c'est
 # le fichiers missing.png qui sera affiché dans les 2 dimensions

 has_attached_file :picture, styles: { original: "1920x1800>", thumb: "200x200>" }, default_url: "/images/:style/missing.png"

 # on s'assure que le fichier envoyé sera de type 'image'
 validates_attachment_content_type :picture, content_type: /\Aimage\/.*\Z/

 # On vérifie que le fichier aura l'extension 'png', 'jpg', 'jpeg'
 validates_attachment_file_name :picture, matches: [/png\Z/, /jpe?g\Z/, /pdf\Z/]

 # On vérifie que l'image envoyé ne fasse pas plus d'un 1M
 validates_with AttachmentSizeValidator, attributes: :picture, less_than: 1.megabytes

 # on vérifie que le champ est bien rempli
 validates :picture, presence: true
 belongs_to :user
 belongs_to :car
end

app/controllers/statements_controller.rb
class StatementsController < ApplicationController
  before_action :set_statement, only: [:show, :edit, :update, :destroy]

  # GET /statements
  # GET /statements.json
  def index
    @statements = Statement.all
  end

  # GET /statements/1
  # GET /statements/1.json
  def show
  end

  # GET /statements/new
  def new
    @statement = Statement.new
  end

  # GET /statements/1/edit
  def edit
  end

  # POST /statements
  # POST /statements.json
  def create
    @statement = Statement.new(statement_params)

    respond_to do |format|
      if @statement.save
        format.html { redirect_to @statement, notice: 'Statement was successfully created.' }
        format.json { render :show, status: :created, location: @statement }
      else
        format.html { render :new }
        format.json { render json: @statement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /statements/1
  # PATCH/PUT /statements/1.json
  def update
    respond_to do |format|
      if @statement.update(statement_params)
        format.html { redirect_to @statement, notice: 'Statement was successfully updated.' }
        format.json { render :show, status: :ok, location: @statement }
      else
        format.html { render :edit }
        format.json { render json: @statement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statements/1
  # DELETE /statements/1.json
  def destroy
    @statement.destroy
    respond_to do |format|
      format.html { redirect_to statements_url, notice: 'Statement was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_statement
      @statement = Statement.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def statement_params
      params.require(:statement).permit(:date, :reason, :kms, :road, :place, :user_id, :picture)
    end
end

app/helpers/statements_helper.rb
module StatementsHelper
end

app/views/statements/_form.html.erb
<%= form_for @statement,html: { multipart: true } do |f| %>
  <% if @statement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@statement.errors.count, "error") %> prohibited this statement from being saved:</h2>

      <ul>
      <% @statement.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :reason %><br>
    <%= f.text_field :reason %>
  </div>
  <div class="field">
    <%= f.label :kms %><br>
    <%= f.number_field :kms %>
  </div>
  <div class="field">
    <%= f.label :road %><br>
    <%= f.text_field :road %>
  </div>
  <div class="field">
    <%= f.label :place %><br>
    <%= f.text_field :place %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :upload%><br>
    <%= f.file_field :picture %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/statements/edit.html.erb
<h1>Editing Statement</h1>

<%= render 'form' %>

<%= link_to 'Show', @statement %> |
<%= link_to 'Back', statements_path %>

app/views/statements/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Statements</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Reason</th>
      <th>Kms</th>
      <th>Road</th>
      <th>Place</th>
      <th>User</th>
      <th>Attachment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @statements.each do |statement| %>
      <tr>
        <td><%= statement.date %></td>
        <td><%= statement.reason %></td>
        <td><%= statement.kms %></td>
        <td><%= statement.road %></td>
        <td><%= statement.place %></td>
        <td><%= statement.user %></td>
        <td><%= image_tag statement.picture.url(:thumb) %></td>
        <td><%= link_to 'Show', statement %></td>
        <td><%= link_to 'Edit', edit_statement_path(statement) %></td>
        <td><%= link_to 'Destroy', statement, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Statement', new_statement_path %>
 <br>

 <% if user_signed_in? %>
 Logged in as <strong><%=current_user.email %></strong>.
 <%= link_to 'Edit profile', edit_user_registration_path, :classe => 'navbar-link' %><br>
 <%= link_to 'Logout', destroy_user_session_path, method: :delete, :class => 'navbar-link' %>
 <% end %>

app/views/statements/new.html.erb
<h1>New Statement</h1>

<%= render 'form' %>

<%= link_to 'Back', statements_path %>

app/views/statements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @statement.date %>
</p>

<p>
  <strong>Reason:</strong>
  <%= @statement.reason %>
</p>

<p>
  <strong>Kms:</strong>
  <%= @statement.kms %>
</p>

<p>
  <strong>Road:</strong>
  <%= @statement.road %>
</p>

<p>
  <strong>Place:</strong>
  <%= @statement.place %>
</p>

<p>
  <strong>User:</strong>
  <%= @statement.user %>
</p>
<p>
  <strong>Attachment:</strong>
  <%= image_tag(@statement.picture(:thumb)) %>
</p>
<%= link_to 'Edit', edit_statement_path(@statement) %> |
<%= link_to 'Back', statements_path %>